# Generated by Django 3.1.3 on 2020-12-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=True)),
                ('heading', models.TextField(max_length=500, unique=True)),
                ('imagelink', models.CharField(max_length=255)),
                ('newslink', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('papername', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
