# Generated by Django 3.1.3 on 2021-01-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.TextField(max_length=120, unique=True),
        ),
    ]
