# Generated by Django 3.1.3 on 2021-01-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speech',
        ),
    ]
