# Generated by Django 3.1.3 on 2021-01-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210109_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
